### ISSUE TITLE
DotNet.exec results are "ignored"

### ISSUE THREAD

**Issue by tebeco** [FakeBuild/fake-netcore-sample#1]
So far when working with CLI execution like 

```fsharp
  DotNet.exec id "clean" ""
  |> ignore
```

the results of the CLI execution is discarded and the execution continue, it should check for exit code and fails to avoid next target to be invoked

**Comment by matthid** [comment]
With `exec` you need to handle the return code manually. That is by design as you can run pretty much any command and might even be interested in the output or the exit code.

**Comment by tebeco** [comment]
yup
i just open issue here in order to point out what’s missing should not be forgotten

**Comment by matthid** [comment]
We could add an `DotNet.execOrFail` if needed

**Comment by tebeco** [comment]
would be nice
